spring.application.name=spring-cloud-stream-aca-other

server.port=8081

#spring.integration.poller.fixed-delay=1000

#spring.cloud.processor.bindings.enrichTransaction-in-0.destination=approvalRequest-out-0
