spring.application.name=spring-cloud-rabbit-csv


spring.cloud.stream.bindings.helper.destination=amq.direct
spring.cloud.stream.bindings.helper.group=helperin
spring.cloud.stream.rabbit.bindings.helper.consumer.bindQueue=false
spring.cloud.stream.rabbit.bindings.helper.consumer.declareExchange=false
spring.cloud.stream.rabbit.bindings.helper.consumer.queueNameGroupOnly=true
